---
title: "Template for hw4"
output: html_notebook
---

```{r}
library(tidyverse)
library(lubridate)
library(rvest)

```

```{r}
air <- read_html("https://www.radarbox.com/statistics/total") %>%
  html_node("table#datatable") %>%
  html_table() %>%
rename(date = Day)
# Трохи приведемо до лау назви колонок, для зручності
colnames(air) <- colnames(air) %>%
  str_replace("  ", "_") %>%
  str_replace(" ", ".") %>%
  str_to_lower()
```

```{r}
air <- air %>%
  mutate(date = as.Date(date)) %>%
  group_by(week(date))
  air
```

```{r}

air <- air %>%
  mutate(date = as.Date(date)) %>%
  select(date,"brazil_non.brazil") 
air
```


```{r}
# df <- read.csv("checkpoints/df-2.csv")

air <- air %>%
              
  mutate(date = as.Date(date))  %>%
  select("date","brazil_non.brazil") %>%
  arrange((date))
  
 
air
```

```{r}
# df <- read.csv("checkpoints/df-3.csv")

  air$year = as.numeric(format(air$date,'%Y')) 
  air$month = as.numeric(format(air$date,'%m'))
  air$day = as.numeric(format(air$date,'%d'))
air[,c("date","year","month", "day")]
```

```{r}
# df <- read.csv("checkpoints/df-4.csv")
air <- air %>%
  group_by(day,month) %>%
 filter(n() == 2)
air
```

```{r}
# df <- read.csv("checkpoints/df-5.csv")
wider_df <- air %>% 
pivot_wider(id_cols = c("day", "month"),
              names_from = "year",
              values_from = "brazil_non.brazil",
              names_prefix = "y")
wider_df
```

```{r}
# wider_df <- read.csv("checkpoints/df-5-wider.csv")

wider_df <- wider_df %>% 
mutate(flights = y2019/y2020,
       date = str_c("2020",month, day, sep="-"),
       date = ymd(date))

wider_df
```

```{r}
prepare_covid <- function(url, col_name) {
  d <- read.csv(url) %>%
    rename(region = Province.State, country = Country.Region) %>%
    pivot_longer(cols = -c(region, country, Lat, Long),
                 names_to = "date",
                 names_prefix = "X",
                 values_to = col_name
                 ) %>%
    mutate(date = mdy(date)) %>%
    select(-c(Lat, Long)) %>%
    group_by(country, date) %>%
    summarise(col_name = sum(get(col_name)))
  
  cnames <- colnames(d)
  cnames[cnames == "col_name"] <- col_name
  colnames(d) <- cnames
  return(d)
}
covid19 <- prepare_covid("https://bit.ly/3aLLfKw", "cases") %>%
  full_join(prepare_covid("https://bit.ly/2XdZ6W0", "recovered")) %>%
  full_join(prepare_covid("https://bit.ly/2yEhPQg", "deaths")) %>%
  mutate(active_cases = cases - recovered - deaths,
         date = as.Date(date))
covid19
```

```{r}
viruses_df <- covid19 %>% 
 filter (country=="Brazil") 


viruses_df 
```

```{r}
df <-viruses_df %>%
  
 filter (country=="Brazil") %>%
 full_join(wider_df,by=c("date")) 
 
df
```

```{r}
# wider_df <- read.csv("checkpoints/df-6-wider.csv") %>%
#   mutate(date = as.Date(date))
```

```{r}
write.csv(df,"BrazilVitaZh.csv")
```

```{r}
read.csv("BrazilVitaZh.csv")
```