---
  title: "my first scraping"
output: html_document
---
  
```{r}
message=FALSE, warning=FALSE, include=FALSE}
install.packages('rvest')    
install.packages('tidyverse')
install.packages("progress")
```

```{r}setup, include=FALSE}
library(rvest)    
library(tidyverse)
library(progress)
```

```{r}
url <- "https://leboutique.com/uk/catalog/women/dress"
content <- read_html(url)
content
```

```{r}
url_template <- "https://leboutique.com/uk/catalog/women/dress?page="
numbers <- str_c(url_template,c(1:5))
```

```{r}
content %>%
  html_nodes("div.prod__name.crop") %>%
  html_text()
```

```{r}
titles <- content %>%
  html_nodes ("div.prod__name.crop") %>%
  html_text() %>%
  str_trim()
titles
```
```{r}
brand <- content %>%
  html_nodes("div.prod__brand.crop") %>%
  html_text() %>%
  str_trim()
brand

```

```{r}
prices <- content %>%
  html_nodes("div.prod__price.color_fire") %>%
  html_text() %>%
  str_trim()
prices
```

```{r}
df <- data.frame(titles = titles, prices = prices, brand=brand)
write.csv (df, "LeBoutiqueDress.csv", 
           row.names = FALSE) 
df
```

```{r}
read.csv("LeBoutiqueDress.csv")
```

```{r}
prices <- c()
titles <- c()
brand <- c()

url_template <- "https://leboutique.com/uk/catalog/women/dress?page="
```

```{r}
for (page in numbers) {
  
  content <- read_html(url)
  
  titles <- content %>%
    html_nodes('div.prod__name.crop') %>%
    html_text() %>%
    str_trim() %>%
    c(titles, .)    
  
  prices <- content %>%
    html_nodes('div.prod__price.color_fire') %>%
    html_text() %>%
    str_trim()  %>%
    c(prices, .)
  
  brand <- content %>%
    html_nodes('div.prod__brand.crop') %>%
    html_attr("href") %>%
    str_trim()  %>%
    c(brand, .)
  
  Sys.sleep(3)    
}
```

```{r}
data.frame(title = titles,
           prices = prices,
           brand =  brand) %>%
  write.csv ("LeBoutiqueDress.csv")

df
```

```{r}
read.csv ("LeBoutiqueDress.csv")
df
```
