---
title: "1, scraper"
output: html_document
---
```{r message=FALSE, warning=FALSE, include=FALSE}
install.packages('rvest')    # install 'rvest' library in R; library and package are synonyms
install.packages('tidyverse')
install.packages("progress")
```

```{r setup, include=FALSE}
library(rvest)    
library(tidyverse)
library(progress)
```

```{r}
url <- "https://leboutique.com/uk/catalog/women/dress"
content <- read_html(url)
content
```

```{r}
url_template <- "https://leboutique.com/uk/catalog/women/dress?page="
numbers <- str_c(url_template,c(1:5))
npages <- 5    # нр: цей рядок стає зайвим
```

```{r}
content %>%
  html_nodes("div.prod__name.crop") %>%
  html_text()
```

```{r}
title <- content %>%
  html_nodes ("div.prod__name.crop") %>%
  html_text() %>%
  str_trim()
title
```

```{r}
price <- content %>%
  html_nodes("div.prod__price.color_fire") %>%
  html_text() %>%
  str_trim()
price
```

```{r}
brand <- content %>%
  html_nodes("div.prod__brand.crop") %>%
  html_text() %>%
  str_trim()
brand
```

```{r}
df <- data.frame(title = title, price = price, brand = brand)
      write.csv (df, "LeBoutiqueDress.csv", 
                 row.names = FALSE) 
df
```

```{r}
read.csv("LeBoutiqueDress.csv")
```

```{r}
npages <- 5   # нр: теж зайва змінна, але це не впливає на програму
price <- c()
title <- c()
brand <- c()

url_template <- "https://leboutique.com/uk/catalog/women/dress?page="
```

```{r}
for (page in numbers) {    # нр: тут уважно: у вас є готовні url-адреси, змінна page
  
  url <- str_c(url_template)    # нр: тут ви кажете, що урл це шаблон без номера сторінки (він на 76 рядку)
 
  content <- read_html(url)    # …і дістаєте html чомусь не для заздалегідь зробленого 'page', а для по суті 'url_template'
  # якщо вставите правильну змінну замість url — все спрацює
  
  title <- content %>%
    html_nodes('div.prod__name.crop') %>%
    html_text() %>%
    str_trim() %>%
    c(title, .)    
  
  price <- content %>%
    html_nodes('div.prod__price.color_fire') %>%
    html_text() %>%
    str_trim()  %>%
    c(price, .)
  
  brand <- content %>%
    html_nodes('div.prod__brand.crop') %>%
    html_attr("href") %>%
    c(brand, .)
  
  Sys.sleep(3)    
}
```

```{r}
data.frame(title = title,
           price = price,
           brand = brand) %>%
write.csv ("LeBoutiqueDress.csv")
            row.names = FALSE
```

```{r}
df <- read.csv("LeBoutiqueDress.csv")
df
```
 
 АААААлілуя, я то зробила)( майжее:(((
